### ISSUE TITLE
PyCUDA's gpuarray.sum produces CUDA memory access violations on multi-GPU setups

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/montblanc#145]
Some sample output from a partial cuda-memcheck run [error.txt](https://github.com/ska-sa/montblanc/files/336810/error.txt):

```bash
========= Invalid __global__ read of size 8
=========     at 0x000000b8 in reduce_kernel_stage1
=========     by thread (0,0,0) in block (0,0,0)
=========     Address 0x810eb80000 is out of bounds
```

This happens in PyCUDA's gpuarray.sum. Looks like the allocation from the DeviceMemoryPool is invalid.

However, it does work if one specifies a single GPU with `CUDA_VISIBLE_DEVICES=0` for instance.

Is the Device Memory Pool associated with the wrong context?

**Comment by sjperkins** [comment]
Loading the kernel seems to fail:

```bash
======================================================================
ERROR: test_medium_budget (test_rime_v5.TestRimeV5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_rime_v5.py", line 67, in test_medium_budget
    with solver(slvr_cfg) as slvr:
  File "/home/sjperkins/montblanc/montblanc/impl/rime/v5/CompositeRimeSolver.py", line 579, in __enter__
    self.initialise()
  File "/home/sjperkins/montblanc/montblanc/impl/rime/v5/CompositeRimeSolver.py", line 977, in initialise
    ex.submit(_init_func).result()
  File "/home/sjperkins/montblanc/.virtualenv/local/lib/python2.7/site-packages/futures-3.0.5-py2.7.egg/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/home/sjperkins/montblanc/.virtualenv/local/lib/python2.7/site-packages/futures-3.0.5-py2.7.egg/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sjperkins/montblanc/montblanc/impl/rime/v5/CompositeRimeSolver.py", line 973, in _init_func
    subslvr.initialise()
  File "/home/sjperkins/montblanc/montblanc/impl/rime/v5/RimeSolver.py", line 134, in initialise
    self.rime_e_beam.initialise(self)
  File "/home/sjperkins/montblanc/montblanc/impl/rime/v5/gpu/RimeEBeam.py", line 29, in initialise
    super(RimeEBeam, self).initialise(solver,stream)
  File "/home/sjperkins/montblanc/montblanc/impl/rime/v4/gpu/RimeEBeam.py", line 359, in initialise
    no_extern_c=True)
  File "/home/sjperkins/montblanc/.virtualenv/local/lib/python2.7/site-packages/pycuda-2016.1.1-py2.7-linux-x86_64.egg/pycuda/compiler.py", line 268, in __init__
    self.module = module_from_buffer(cubin)
LaunchError: cuModuleLoadDataEx failed: launch failed - 
```
[This](https://lists.tiker.net/pipermail/pycuda/2012-May/003867.html) PyCUDA mailing list entry suggests this happens because of thread contention for a pipe to the NVCC compiler.

**Comment by sjperkins** [comment]
Fixed by https://github.com/ska-sa/hypercube/pull/15 and [upgrade](https://github.com/ska-sa/montblanc/commit/046abed9c97479282d61a32b3e3dbb3a060100b8) to hypercube 0.2.1-alpha4.
