### ISSUE TITLE
Hypercube has no attribute 'dim_local_size'

### ISSUE THREAD

**Issue by bennahugo** [ska-sa/montblanc#179]
Something is going wonkey deep inside montblanc... as caught by the Jenkins CI:
```
  File "/ddfvenv/local/lib/python2.7/site-packages/DDFacet/Imager/ClassDeconvMachine.py", line 665, in GivePredict
    mb_machine = ClassMontblancMachine(self.GD, self.FacetMachine.Npix, self.FacetMachine.CellSizeRad)
  File "/ddfvenv/local/lib/python2.7/site-packages/DDFacet/Imager/ClassMontblancMachine.py", line 42, in __init__
    self._solver = montblanc.rime_solver(slvr_cfg)
  File "/montblanc/montblanc/__init__.py", line 148, in rime_solver
    return montblanc.factory.rime_solver(slvr_cfg)
  File "/montblanc/montblanc/factory.py", line 182, in rime_solver
    return RimeSolver(slvr_cfg)
  File "/montblanc/montblanc/impl/rime/tensorflow/RimeSolver.py", line 86, in __init__
    mbu.register_default_dimensions(cube, slvr_cfg)
  File "/montblanc/montblanc/util/__init__.py", line 505, in register_default_dimensions
    ntime, na, nchan, npol = cube.dim_local_size(
AttributeError: 'HyperCube' object has no attribute 'dim_local_size'

 - 23:10:24 - DDFacet                   | [0.7/0.7 1.2/1.4 0.1Gb] [1m[91mThere was a problem after 0m11.6s, if you think this is a bug please open an issue, quote your version of DDFacet and attach your logfile[0m[0m
 - 23:10:24 - DDFacet                   | [0.7/0.7 1.2/1.4 0.1Gb] [1m[91mYou are using DDFacet revision: 0.0.1[0m[0m
 - 23:10:24 - DDFacet                   | [0.7/0.7 1.2/1.4 0.1Gb] [1m[91mYour logfile is available here: /test_output/TestMontblancPredict.run.log[0m[0m
 - 23:10:24 - DDFacet                   | [0.7/0.7 1.2/1.4 0.1Gb] Traceback (most recent call last):
  File "/ddfvenv/bin/DDF.py", line 498, in <module>
    main(OP, messages)
  File "/ddfvenv/bin/DDF.py", line 360, in main
    Imager.GivePredict()
  File "/ddfvenv/local/lib/python2.7/site-packages/DDFacet/Imager/ClassDeconvMachine.py", line 665, in GivePredict
    mb_machine = ClassMontblancMachine(self.GD, self.FacetMachine.Npix, self.FacetMachine.CellSizeRad)
  File "/ddfvenv/local/lib/python2.7/site-packages/DDFacet/Imager/ClassMontblancMachine.py", line 42, in __init__
    self._solver = montblanc.rime_solver(slvr_cfg)
  File "/montblanc/montblanc/__init__.py", line 148, in rime_solver
    return montblanc.factory.rime_solver(slvr_cfg)
  File "/montblanc/montblanc/factory.py", line 182, in rime_solver
    return RimeSolver(slvr_cfg)
  File "/montblanc/montblanc/impl/rime/tensorflow/RimeSolver.py", line 86, in __init__
    mbu.register_default_dimensions(cube, slvr_cfg)
  File "/montblanc/montblanc/util/__init__.py", line 505, in register_default_dimensions
    ntime, na, nchan, npol = cube.dim_local_size(
AttributeError: 'HyperCube' object has no attribute 'dim_local_size'
```

**Comment by sjperkins** [comment]
Fix incoming with https://github.com/cyriltasse/DDFacet/pull/281.

**Comment by sjperkins** [comment]
Fixed by https://github.com/ska-sa/montblanc/commit/ae6b323bfd46353585977356604453e8b2442e94
